# Generated by Django 5.1.4 on 2026-04-27 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_recipe_id', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('ingredients_summary', models.TextField(blank=True, default='')),
                ('answer_snippet', models.TextField(blank=True, default='', help_text='LLM 답변 일부(저장 시점 미리보기)')),
                ('source', models.CharField(choices=[('db', 'DB'), ('web', '웹 검색'), ('llm', 'LLM 추정')], default='db', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '즐겨찾기 레시피',
                'verbose_name_plural': '즐겨찾기 레시피들',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mongo_recipe_id', ''), _negated=True), fields=('user', 'mongo_recipe_id'), name='uniq_user_recipe_when_id_present')],
            },
        ),
    ]
