# Generated by Django 5.1.4 on 2026-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_chatmessage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.CharField(blank=True, default='없음', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='cooking_time',
            field=models.CharField(blank=True, default='20분', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='difficulty',
            field=models.CharField(blank=True, default='초보', max_length=20),
        ),
    ]
